
export default {
    'UNFOCUS': 'UNFOCUS',
    'CHANGE_TIME': 'CHANGE_TIME',
    'CHANGE_ACTIVE_TIME_LEVEL': 'CHANGE_ACTIVE_TIME_LEVEL',
    'FOCUS': 'FOCUS',
    'UNSELECT_SATELLITE': 'UNSELECT_SATELLITE',
    'SELECT_SATELLITE': 'SELECT_SATELLITE',
    'FOLLOW_NOW': 'FOLLOW_NOW',
    'CHANGE_TIME_LINE_DAY_WIDTH': 'CHANGE_TIME_LINE_DAY_WIDTH',
}