
export default {
    'CHANGE_LANDSCAPE': 'CHANGE_LANDSCAPE',
    'FOCUS_SATELLITE': 'FOCUS_SATELLITE',
    'TOGGLE_LAYER': 'TOGGLE_LAYER',
    'PREVENT_RELOAD_LAYERS': 'PREVENT_RELOAD_LAYERS',
    'DEACTIVATE_LAYER': 'DEACTIVATE_LAYER',
    'ACTIVATE_LAYER': 'ACTIVATE_LAYER',
    'UPDATE_ACTIVE_LAYER': 'UPDATE_ACTIVE_LAYER',
    'CHANGE_SELECTTIME': 'CHANGE_SELECTTIME',
    'CHANGE_CURRENTTIME': 'CHANGE_CURRENTTIME',
    'CHANGE_ACTIVE_TIME_LEVEL': 'CHANGE_ACTIVE_TIME_LEVEL',
    'FOLLOW_NOW': 'FOLLOW_NOW',
    'TRACK_TIME': 'TRACK_TIME',
    'UPDATE_INFO_MODAL': 'UPDATE_INFO_MODAL',
    'SET_ACTIVE_INFO_MODAL': 'SET_ACTIVE_INFO_MODAL',
    'SET_ORBITS': 'SET_ORBITS',
    'SET_ACQUISITION_PLANS': 'SET_ACQUISITION_PLANS',
    'MAP_ADD_VISIBLE_ACQUISITION_PLAN': 'MAP_ADD_VISIBLE_ACQUISITION_PLAN',
    'DATA_ACQUISITIONPLANS_SET_VISIBLE_COUNT': 'DATA_ACQUISITIONPLANS_SET_VISIBLE_COUNT',
    'MAP_REMOVE_VISIBLE_ACQUISITION_PLAN': 'MAP_REMOVE_VISIBLE_ACQUISITION_PLAN',
    'DATA_UPDATE_ACQUISITIONPLANS': 'DATA_UPDATE_ACQUISITIONPLANS',
    'DATA': {
        'SATELLITES': {
            'SET_HEADING': 'DATA.SATELLITES.SET_HEADING',
            'SET_HEADING_AND_UPDATE_VIEW_HEADING_CORRECTION': 'DATA.SATELLITES.SET_HEADING_AND_UPDATE_VIEW_HEADING_CORRECTION',
        }
    },
    'COMPONENT': {
        'SET': 'COMPONENT.SET',
        'UPDATE': 'COMPONENT.UPDATE',
        'CLEAR': 'COMPONENT.CLEAR',
    },
    'COMPONENTS' :{
        'SEARCH': {
            'SET_PRODUCTS': 'COMPONENTS.SEARCH.SET_PRODUCTS',
        },
        'SEARCH_TOOLBAR': {
            'CLEAR': 'COMPONENTS.SEARCH_TOOLBAR.CLEAR',
        }
    },
    'MAP': {
        'SET_VIEW': 'MAP.SET_VIEW',
        'UPDATE_VIEW': 'MAP.UPDATE_VIEW',
        'SET_NAVIGATOR': 'MAP.SET_NAVIGATOR',
        'REMOVE_STATISTICS_LAYER': 'REMOVE_STATISTICS_LAYER',
        'ADD_STATISTICS_LAYER': 'ADD_STATISTICS_LAYER',
        'UPDATE_STATISTICS': 'UPDATE_STATISTICS',
        'UPDATE_VIEW_HEADING_CORRECTION_FROM_FOCUSED_SATELLITE': 'MAP.UPDATE_VIEW_HEADING_CORRECTION_FROM_FOCUSED_SATELLITE',
    },
}