
export default {
    'FOCUS_SATELLITE': 'FOCUS_SATELLITE',
    'TOGGLE_LAYER': 'TOGGLE_LAYER',
    'PREVENT_RELOAD_LAYERS': 'PREVENT_RELOAD_LAYERS',
    'DEACTIVATE_LAYER': 'DEACTIVATE_LAYER',
    'ACTIVATE_LAYER': 'ACTIVATE_LAYER',
    'UPDATE_ACTIVE_LAYER': 'UPDATE_ACTIVE_LAYER',
    'CHANGE_SELECTTIME': 'CHANGE_SELECTTIME',
    'CHANGE_CURRENTTIME': 'CHANGE_CURRENTTIME',
    'CHANGE_ACTIVE_TIME_LEVEL': 'CHANGE_ACTIVE_TIME_LEVEL',
    'FOLLOW_NOW': 'FOLLOW_NOW',
    'CHANGE_TIME_LINE_DAY_WIDTH': 'CHANGE_TIME_LINE_DAY_WIDTH',
    'TIME_LINE_SET_MOUSE_TIME': 'TIME_LINE_SET_MOUSE_TIME',
    'SET_OVERLAYS': 'SET_OVERLAYS',
    'UPDATE_INFO_MODAL': 'UPDATE_INFO_MODAL',
    'COMPONENTS': {
        'SET': 'COMPONENTS.SET',
        'UPDATE': 'COMPONENTS.UPDATE',
    }
}